### ISSUE TITLE
RTE in method signature parsing on unknown code

### ISSUE THREAD

**Issue by nherbaut** [nh-group/DEXTORM#12]
@NathanHayoun got this exception while working with unknown code

```
[STAR] computing req from /tmp/dextorm17012972130658167357/srv/src/main/java/com/sap/cloud/conso/datamapping/tms/services/HierarchyTools.java
java.lang.RuntimeException: failed to convert type CDS_NAME_MANUAL_V2
        at fr.pantheonsorbonne.cri.reqmapping.impl.Utils.typeToCodeJVM(Utils.java:30)
        at fr.pantheonsorbonne.cri.reqmapping.impl.gumTree.visitor.MethodDeclarationVisitor.extractMethodLikeParameters(MethodDeclarationVisitor.java:94)
        at fr.pantheonsorbonne.cri.reqmapping.impl.gumTree.visitor.MethodDeclarationVisitor.startTree(MethodDeclarationVisitor.java:62)
        at fr.pantheonsorbonne.cri.reqmapping.impl.gumTree.visitor.JavaParserTreeExclusiveCompositeVisitor.startTree(JavaParserTreeExclusiveCompositeVisitor.java:38)
        at fr.pantheonsorbonne.cri.reqmapping.impl.gumTree.visitor.ClassOrInterfaceDeclarationVisitor.startTree(ClassOrInterfaceDeclarationVisitor.java:31)
        at fr.pantheonsorbonne.cri.reqmapping.impl.gumTree.visitor.JavaParserTreeExclusiveCompositeVisitor.startTree(JavaParserTreeExclusiveCompositeVisitor.java:38)
        at fr.pantheonsorbonne.cri.reqmapping.impl.gumTree.visitor.CompilationUnitVisitor.startTree(CompilationUnitVisitor.java:33)
        at com.github.gumtreediff.tree.TreeVisitor.visitTree(TreeVisitor.java:39)
        at fr.pantheonsorbonne.cri.reqmapping.impl.gumTree.GumTreeFacade.getReqMatcher(GumTreeFacade.java:77)
        at fr.pantheonsorbonne.cri.reqmapping.impl.gumTree.GumTreeFacade.getReqMatcher(GumTreeFacade.java:149)
        at fr.pantheonsorbonne.cri.reqmapping.impl.gumTree.CachedGumTreeFacade.getReqMatcher(CachedGumTreeFacade.java:44)
        at fr.pantheonsorbonne.cri.reqmapping.impl.gumTree.GumTreeFileRequirementMappingProvider.getReqMatcher(GumTreeFileRequirementMappingProvider.java:84)
        at fr.pantheonsorbonne.cri.reqmapping.impl.GitRepoRequirementMappingProvider.lambda$visitFile$3(GitRepoRequirementMappingProvider.java:87)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by nherbaut** [comment]
added a typed exception to log the trace, and prevent the RTE from stopping the processing
